### ISSUE TITLE
How is this different from react-native-draggable-flatlist?

### ISSUE THREAD

**Issue by kevgrig** [thomasrovayaz/react-native-draggable-dynamic-flatlist#1]
Hi, I was just about to install `react-native-draggable-flatlist` but found your package on npm and I'm just curious how this package is different from `react-native-draggable-flatlist`?

**Comment by thomasrovayaz** [comment]
Hello, react-native-draggable-flatlist is good but it doesn't work when item's sizes are changing. The positions (x and y) are not calculated properly. It's using measure functions which doesn't work perfectly on react-native, I had lot of unsolvable bugs (especially on android). Also, the measure function doesn't work when the item is hidden on a flatlist (out of the screen), so if you have big items, it doesn't work really well.
I refactored the whole measuring system by calculating all the positions manually.
My library is using the onLayout property on each item and scrollview which makes it more stable with dynamic content. onLayout works perfectly on react-native and I have no problem with dynamic content.

**Comment by kevgrig** [comment]
Good answer. You might want to put that in the README to help new users see the difference.

**Comment by thomasrovayaz** [comment]
It's changed, thank you
