### ISSUE TITLE
Last item always move with second last item 

### ISSUE THREAD

**Issue by appdeveloperhw** [thomasrovayaz/react-native-draggable-dynamic-flatlist#13]
Last item always stcuk with second last item

![ezgif-7-ffdc9db8a884](https://user-images.githubusercontent.com/46839710/76619883-bdd59600-654d-11ea-8e36-65b6e78e4a71.gif)

**Comment by xuho** [comment]
Same issue, any workaround for this?

**Comment by premhowli** [comment]
facing the same issue.

**Comment by appdeveloperhw** [comment]
Hello,

i just moved back to [https://github.com/computerjazz/react-native-draggable-flatlist](https://github.com/computerjazz/react-native-draggable-flatlist) it is working fine now. 

i was move here because react-native-draggable-flatlist was not working well with dynamic flatlist when we add or remove item from list but now its look like they solved it.

```
<DraggableFlatList
                    data={this.state.data}
                    renderItem={this.renderItem}
                    extraData={this.state}
                    layoutInvalidationKey={this.state.changecounter}
                    keyExtractor={(item, index) => `draggable-item-${index}`}
                    scrollPercent={0}
                    onDragEnd={({ data }) => { console.log(data); this.notechanges(data); }}
                    ListEmptyComponent={() => {}} />
```

one thing to note here is **layoutInvalidationKey** you should change it when you add, remove or size of item change.

**react-native-draggable-dynamic-flatlist** is bugy

**Comment by dev-sathish** [comment]
@appdeveloperhw Hi,
Have you found any solution for this? same here..! can't able to place our item in the required place.
