### ISSUE TITLE
0.63 useNativeDriver Problem

### ISSUE THREAD

**Issue by ismailyagci** [thomasrovayaz/react-native-draggable-dynamic-flatlist#19]
Hello.When I try to use the library in 0.63, I get a problem with useNativeDriver. I request it to be fixed.

**Comment by MarioDavidUzcategui** [comment]
Hello. I installed this library 6 days ago and show up the useNativeDriver warning. In the package.json is the 1.0.4 version.

**Comment by khushal87** [comment]
Admins, do we have any solution for the same?

**Comment by sarahsidek** [comment]
is that any solution for this problem?

**Comment by softiomx** [comment]
is that any solution for this problem?
